export const VIEW_ALL_COURSES = 'VIEW_ALL_COURSES';
export const VIEW_CATEGORY = 'VIEW_CATEGORY';
export const BACK_TO_CATEGORIES = 'BACK_TO_CATEGORIES';
export const CATEGORIES = 'CATEGORIES';
export const CATEGORY =  'CATEGORY';
